import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [mensaje, setMensaje] = useState("")

  const onClick = (boton) => {
    if (boton === "si") {
      setMensaje("VAMOS TE QUIERO")
    }
    else {
      setMensaje("MORITE GATO")
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className='text-4xl '>Me merezco un aumento?</h1>
        <p className='text-xl mt-2 text-white'>{mensaje}</p>
        <div className='flex space-x-3 my-10'>
          <button onClick={() => onClick("si")} className='hover:bg-red-400 bg-red-200 text-white px-4 py-1 text-lg'> si </button>
          <button onClick={() => onClick("no")}  >no</button>
        </div>
        <img src="https://www.clarin.com/img/2019/03/26/Ng7jC4r07_720x0__1.jpg" alt="" />
      </main>
    </>
  )
}
